### ISSUE TITLE
作为模板复杂度过高

### ISSUE THREAD

**Issue by zangguojun** [Godiswill/cra-crx-boilerplate#2]
感觉在运行npm run eject之后，项目变得比较乱了，（看不太适合新手），我再想能不能使用类似config-overrides来替代。

**Comment by zangguojun** [comment]
好好看了一下项目  貌似真不能使用简单的npm包来实现

**Comment by dalaobb** [comment]
> 感觉在运行npm run eject之后，项目变得比较乱了，（看不太适合新手），我再想能不能使用类似config-overrides来替代。

config-overrides 试过了，不行。要么自己从零开始配。单纯用来直接开发 crx 的话还是没有障碍的。

**Comment by zangguojun** [comment]
嗯 对的 我一开始没看代码的时候 我以为可以 但是 看完源码 的确比较难搞 config-overrides 确实难以达到
